### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Conradium** [adrien-dimitri/tts-rvc#1]
Hello! Speed 1.0-2.0 does not really make any significant difference on the playback. Is there anyway I can make the speech faster?

**Comment by adrien-dimitri** [comment]
Ok I see what you mean. In app/routers/tts.py, the variables `speed` and `emotion` from line 31 and 32 are not properly configured in line 52. I will fix this shortly. Thanks for pointing this out!

**Comment by adrien-dimitri** [comment]
I fixed the parameters now. If you still want to significantly alter the speed, let me know, I will show you how you can add a piece of code to do it. Thanks for the feedback Conradium 😁

**Comment by Conradium** [comment]
Thanks for fixing it! I did not realize I made this issue, I was half drunk yesterday. Sorry for not pointing out where it went wrong.
